source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'rails-api'

gem 'rack-cors'
gem 'faker'
gem 'active_model_serializers', github: 'rails-api/active_model_serializers',
                                tag: 'v0.10.0.rc4'


group :development do
  gem 'sqlite3'
  gem 'spring'
end
